import importlib
import sys

from .api import WrapPolicy, fully_shard, matrix_fully_shard
from .planning.auto_planner import (
    AutoPlannerReportRow,
    auto_group_plan,
    build_auto_planner_report,
    format_auto_planner_report,
    make_muon_shard_aware_group_planner,
)
from .runtime.buffer_pool import FullParamBufferPool, clear_global_full_param_buffer_pool
from .runtime.elastic_param_buffer import (
    ElasticParamBuffer,
    ElasticParamBufferLayout,
    ElasticParamBufferWorkspace,
    ElasticParamBufferWorkspaceLease,
    ElasticParamBufferWorkspacePlan,
    rank_segments_are_rank_contiguous_chunks,
)
from .checkpoint import (
    get_model_state_dict,
    get_optimizer_state_dict,
    get_state_dict,
    load_matrix_dcp,
    load_matrix_dcp_full_state,
    load_matrix_state_dict,
    patch_model_state_dict,
    patch_optimizer_state_dict,
    matrix_get_state_dict,
    matrix_set_state_dict,
    matrix_state_dict,
    save_matrix_dcp,
    set_model_state_dict,
    set_optimizer_state_dict,
    set_state_dict,
)
from .planning.constraints import (
    ParamShardConstraints,
    ShardConstraint,
    constraint_counts,
    infer_group_constraints,
    infer_param_constraints,
)
from .runtime.param_group import (
    FSDPLifecycleState,
    FSDPRuntimeState,
    MatrixFSDPNoSync,
    MatrixFSDPParamGroup,
)
from .planning.layout_validator import RuntimeLayoutCompatibility, explain_runtime_layout_compatibility, validate_runtime_layout
from .core.managed_param import ParamRuntimeKind, ParamShardHint
from .core.mesh import (
    DataParallelMeshDims,
    DeviceMeshMetadata,
    infer_replicate_mesh_dim,
    infer_shard_mesh_dim,
    mesh_coordinate,
    mesh_dim_name,
    mesh_dim_names,
    mesh_metadata,
    mesh_shape,
    normalize_mesh_dim,
)
from .optim import (
    DEFAULT_MUON_ADJUST_LR_FN,
    ClassifiedMatrixOptimizerParams,
    MixedMuonAdamWOptimizer,
    PreparedMatrixOptimizer,
    MatrixFSDPOptimizer,
    MatrixOptimizerConfig,
    MatrixOptimizerParamGroupSummary,
    classify_matrix_optimizer_params,
    configure_optimizer,
    configure_matrix_optimizer,
    install_matrix_optimizer_auto_prepare,
    make_mixed_muon_adamw_optimizer,
    prepare_matrix_optimizer,
)
from .optim.state import (
    LocalOptimizerParamInfo,
    LocalOptimizerStateTensor,
    OptimizerStateSummary,
    MatrixFSDPOptimizerStateManager,
)
from .planning.planner import (
    expert_owner_tail_plan,
    fsdp2_chunk_plan,
    hinted_ordered_group_plan,
    load_balanced_matrix_owner_tail_plan,
    ordered_matrix_owner_tail_plan,
)
from .planning.planner_eval import (
    GroupPlanner,
    PlannerCandidate,
    PlannerCostBreakdown,
    PlannerCostWeights,
    PlannerLayoutContract,
    PlannerResourceEstimate,
    PlannerResult,
    call_group_planner,
    estimate_layout_resources,
    normalize_planner_candidates,
    planner_display_name,
    planner_result_from_output,
)
from .core.placement import (
    PlacementCompatibility,
    MatrixShard,
    MatrixShardPlacement,
    explain_matrix_shard_compatibility,
    is_matrix_shard_compatible_plan,
    is_matrix_shard_placement,
    matrix_shard_from_layout,
    matrix_shard_from_plan,
    shard_sizes_to_matrix_local_units,
)
from .runtime.scheduler import (
    BackwardPrefetchTiming,
    PrefetchPolicy,
    PrefetchProfileResult,
    MatrixFSDPScheduler,
    MatrixFSDPSchedulerConfig,
)
from .runtime.runtime_event import RuntimeEvent
from .runtime.runtime import CommBufferId, PlannerGroupId, RuntimeParamGroupId, RuntimeUnitId, RuntimeUnitMetadata
from .planning.shard_hint import build_shard_hints, moe_expert_owner_rule
from .core.state import MatrixShardedState, matrix_shard_metadata, matrix_sharded_state_metadata
from .runtime.summary import (
    format_param_group_summary,
    format_runtime_events,
    summarize_param_groups,
    summarize_runtime_events,
)
from .runtime.unit_collection import collect_param_groups
from .core.torch_dtensor import make_matrix_dtensor, make_matrix_placements
from .policy.wrap import and_policy, module_type_policy, not_policy, or_policy, size_based_policy

__version__ = "0.1.0"

_MODULE_ALIASES = {
    "auto_planner": "planning.auto_planner",
    "buffer_pool": "runtime.buffer_pool",
    "checkpoint": "checkpoint",
    "collectives": "runtime.collectives",
    "constraints": "planning.constraints",
    "flat_buffer": "runtime.flat_buffer",
    "fsdp_unit": "runtime.fsdp_unit",
    "param_group": "runtime.param_group",
    "grad_bucket": "runtime.grad_bucket",
    "hooks": "runtime.hooks",
    "kernels": "kernels",
    "layout": "core.layout",
    "layout_report": "planning.layout_report",
    "layout_validator": "planning.layout_validator",
    "managed_param": "core.managed_param",
    "mesh": "core.mesh",
    "mixed_precision": "core.mixed_precision",
    "optim_state": "optim.state",
    "placement": "core.placement",
    "planner": "planning.planner",
    "planner_eval": "planning.planner_eval",
    "runtime_event": "runtime.runtime_event",
    "scheduler": "runtime.scheduler",
    "shard_hint": "planning.shard_hint",
    "state": "core.state",
    "summary": "runtime.summary",
    "torch_dtensor": "core.torch_dtensor",
    "unit_collection": "runtime.unit_collection",
    "wrap": "policy.wrap",
}

for _alias, _target in _MODULE_ALIASES.items():
    sys.modules[f"{__name__}.{_alias}"] = importlib.import_module(f".{_target}", __name__)

__all__ = [
    "CommBufferId",
    "ClassifiedMatrixOptimizerParams",
    "DEFAULT_MUON_ADJUST_LR_FN",
    "DataParallelMeshDims",
    "DeviceMeshMetadata",
    "FSDPLifecycleState",
    "FSDPRuntimeState",
    "FullParamBufferPool",
    "GroupPlanner",
    "ParamShardHint",
    "ParamRuntimeKind",
    "PlacementCompatibility",
    "BackwardPrefetchTiming",
    "PrefetchPolicy",
    "PrefetchProfileResult",
    "PlannerGroupId",
    "PlannerCandidate",
    "PlannerCostBreakdown",
    "PlannerCostWeights",
    "PlannerLayoutContract",
    "PlannerResourceEstimate",
    "PlannerResult",
    "ParamShardConstraints",
    "MixedMuonAdamWOptimizer",
    "PreparedMatrixOptimizer",
    "MatrixFSDPOptimizer",
    "MatrixFSDPNoSync",
    "MatrixOptimizerConfig",
    "MatrixOptimizerParamGroupSummary",
    "MatrixFSDPOptimizerStateManager",
    "MatrixFSDPScheduler",
    "MatrixFSDPSchedulerConfig",
    "MatrixFSDPParamGroup",
    "MatrixShard",
    "MatrixShardPlacement",
    "MatrixShardedState",
    "RuntimeUnitId",
    "RuntimeUnitMetadata",
    "RuntimeEvent",
    "RuntimeParamGroupId",
    "RuntimeLayoutCompatibility",
    "ShardConstraint",
    "WrapPolicy",
    "LocalOptimizerParamInfo",
    "LocalOptimizerStateTensor",
    "OptimizerStateSummary",
    "and_policy",
    "AutoPlannerReportRow",
    "auto_group_plan",
    "build_shard_hints",
    "build_auto_planner_report",
    "call_group_planner",
    "classify_matrix_optimizer_params",
    "clear_global_full_param_buffer_pool",
    "constraint_counts",
    "collect_param_groups",
    "configure_optimizer",
    "configure_matrix_optimizer",
    "explain_matrix_shard_compatibility",
    "explain_runtime_layout_compatibility",
    "expert_owner_tail_plan",
    "estimate_layout_resources",
    "format_runtime_events",
    "format_auto_planner_report",
    "format_param_group_summary",
    "fully_shard",
    "fsdp2_chunk_plan",
    "get_model_state_dict",
    "get_optimizer_state_dict",
    "get_state_dict",
    "hinted_ordered_group_plan",
    "infer_replicate_mesh_dim",
    "infer_group_constraints",
    "infer_param_constraints",
    "infer_shard_mesh_dim",
    "is_matrix_shard_compatible_plan",
    "is_matrix_shard_placement",
    "load_balanced_matrix_owner_tail_plan",
    "module_type_policy",
    "moe_expert_owner_rule",
    "make_matrix_dtensor",
    "make_matrix_placements",
    "make_muon_shard_aware_group_planner",
    "make_mixed_muon_adamw_optimizer",
    "install_matrix_optimizer_auto_prepare",
    "mesh_coordinate",
    "mesh_dim_name",
    "mesh_dim_names",
    "mesh_metadata",
    "mesh_shape",
    "normalize_planner_candidates",
    "normalize_mesh_dim",
    "not_policy",
    "ordered_matrix_owner_tail_plan",
    "or_policy",
    "patch_model_state_dict",
    "patch_optimizer_state_dict",
    "planner_display_name",
    "planner_result_from_output",
    "prepare_matrix_optimizer",
    "load_matrix_dcp",
    "load_matrix_dcp_full_state",
    "load_matrix_state_dict",
    "matrix_get_state_dict",
    "matrix_set_state_dict",
    "matrix_fully_shard",
    "matrix_shard_metadata",
    "matrix_sharded_state_metadata",
    "matrix_state_dict",
    "save_matrix_dcp",
    "set_model_state_dict",
    "set_optimizer_state_dict",
    "set_state_dict",
    "matrix_shard_from_layout",
    "matrix_shard_from_plan",
    "shard_sizes_to_matrix_local_units",
    "size_based_policy",
    "summarize_param_groups",
    "summarize_runtime_events",
    "validate_runtime_layout",
]
